# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Alisson\Documents\projetos\Prime-Survivor-Log-Bot-2\src\views\ui\log_bot.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 637)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\Alisson\\Documents\\projetos\\Prime-Survivor-Log-Bot-2\\src\\views\\ui\\../../assets/logbot.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 137, 1);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(15, 15, 15);\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.blue_frame = QtWidgets.QFrame(self.centralwidget)
        self.blue_frame.setMaximumSize(QtCore.QSize(16777215, 121))
        self.blue_frame.setStyleSheet("/*background-color: rgb(0, 12, 255);")
        self.blue_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blue_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.blue_frame.setObjectName("blue_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.blue_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.blue_frame)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 137, 1);\n"
"    font-size: 30px;\n"
"    font-family: \"Arial Black\";\n"
"    background: transparent;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.blue_frame)
        self.imagemlogo = QtWidgets.QFrame(self.centralwidget)
        self.imagemlogo.setMaximumSize(QtCore.QSize(16777215, 250))
        self.imagemlogo.setStyleSheet("")
        self.imagemlogo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.imagemlogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.imagemlogo.setObjectName("imagemlogo")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.imagemlogo)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.imagemlogo)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(200, 200))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("c:\\Users\\Alisson\\Documents\\projetos\\Prime-Survivor-Log-Bot-2\\src\\views\\ui\\../../assets/log_bot_logo.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.imagemlogo)
        self.green_frame = QtWidgets.QFrame(self.centralwidget)
        self.green_frame.setMinimumSize(QtCore.QSize(0, 130))
        self.green_frame.setMaximumSize(QtCore.QSize(16777215, 130))
        self.green_frame.setStyleSheet("/*background-color: rgb(0, 255, 42);")
        self.green_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.green_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.green_frame.setObjectName("green_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.green_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.green_frame)
        self.label_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(255, 137, 1);\n"
"    font-size: 20px;\n"
"    font-family: \"Arial Black\";\n"
"    background: transparent;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.Combo_Resolution = QtWidgets.QComboBox(self.green_frame)
        self.Combo_Resolution.setMinimumSize(QtCore.QSize(300, 0))
        self.Combo_Resolution.setMaximumSize(QtCore.QSize(500, 16777215))
        self.Combo_Resolution.setStyleSheet("QComboBox {\n"
"    border: 0px solid rgb(45, 45, 45);\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    background-color: rgb(24, 24, 24);\n"
"    color: rgb(80, 80, 80);\n"
"    font-size: 18px;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid rgb(255, 137, 1);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 30px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    width: 14px;\n"
"    height: 14px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid rgb(27, 27, 27);\n"
"    background-color: rgb(24, 24, 24);\n"
"    selection-background-color: rgb(255, 137, 1);\n"
"    selection-color: rgb(255, 255, 255);\n"
"    color: rgb(220, 220, 220);\n"
"    font-size: 15px;\n"
"}")
        self.Combo_Resolution.setObjectName("Combo_Resolution")
        self.gridLayout.addWidget(self.Combo_Resolution, 0, 2, 1, 1)
        self.LineEdit_webhook = QtWidgets.QLineEdit(self.green_frame)
        self.LineEdit_webhook.setMaximumSize(QtCore.QSize(500, 16777215))
        self.LineEdit_webhook.setStyleSheet("QLineEdit {\n"
"border: 0px solid rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"padding: 15px;\n"
"background-color: rgb(24, 24, 24);\n"
"color: rgb(80, 80, 80);\n"
"    font: 87 12pt \"Arial Black\";\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"border: 2px solid rgb(27, 27, 27);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"border: 2px solid rgb(255, 137, 1);\n"
"color: rgb(255, 255, 255)\n"
"}\n"
"\n"
"")
        self.LineEdit_webhook.setObjectName("LineEdit_webhook")
        self.gridLayout.addWidget(self.LineEdit_webhook, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.green_frame)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(255, 137, 1);\n"
"    font-size: 20px;\n"
"    font-family: \"Arial Black\";\n"
"    background: transparent;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.green_frame)
        self.red = QtWidgets.QFrame(self.centralwidget)
        self.red.setMinimumSize(QtCore.QSize(0, 0))
        self.red.setMaximumSize(QtCore.QSize(16777215, 92))
        self.red.setStyleSheet("/*background-color: rgb(255, 0, 4);")
        self.red.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.red.setFrameShadow(QtWidgets.QFrame.Raised)
        self.red.setObjectName("red")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.red)
        self.horizontalLayout_5.setSpacing(15)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.btn_start = QtWidgets.QPushButton(self.red)
        self.btn_start.setMinimumSize(QtCore.QSize(285, 80))
        self.btn_start.setMaximumSize(QtCore.QSize(300, 80))
        self.btn_start.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 137, 1);\n"
"border: 3px outset rgb(93, 49, 0);\n"
"border-radius: 10px;\n"
"color: rgb(15, 15, 15);\n"
"font-size: 20px;\n"
"font-family: \"Arial Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 17, 0);\n"
"background-color: rgb(215, 97, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 3px inset rgb(93, 49, 0);\n"
"color: rgb(15, 15, 15);\n"
"background-color: rgb(255, 17, 0);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #cccccc; /* Cinza */\n"
"border: 2px solid #999999;\n"
"color: #666666; /* Texto cinza escuro */\n"
"}\n"
"")
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout_5.addWidget(self.btn_start)
        self.check_test = QtWidgets.QCheckBox(self.red)
        self.check_test.setMaximumSize(QtCore.QSize(114, 16777215))
        self.check_test.setStyleSheet("QCheckBox {\n"
"    color: rgb(120, 120, 120);\n"
"    font-size: 16px;\n"
"    font-family: \"Arial\";\n"
"    spacing: 10px;\n"
"}\n"
"\n"
"QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 6px;\n"
"    background-color: rgb(24, 24, 24);\n"
"    border: 2px solid rgb(45, 45, 45);\n"
"}\n"
"\n"
"QCheckBox::indicator:hover {\n"
"    border: 2px solid rgb(255, 137, 1);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked {\n"
"    background-color: rgb(255, 137, 1);\n"
"    border: 2px solid rgb(255, 137, 1);\n"
"}\n"
"\n"
"QCheckBox::indicator:checked:hover {\n"
"    background-color: rgb(255, 160, 40);\n"
"    border: 2px solid rgb(255, 160, 40);\n"
"}\n"
"\n"
"QCheckBox:checked {\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.check_test.setObjectName("check_test")
        self.horizontalLayout_5.addWidget(self.check_test)
        self.btn_stop = QtWidgets.QPushButton(self.red)
        self.btn_stop.setMinimumSize(QtCore.QSize(285, 80))
        self.btn_stop.setMaximumSize(QtCore.QSize(300, 80))
        self.btn_stop.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 137, 1);\n"
"border: 3px outset rgb(93, 49, 0);\n"
"border-radius: 10px;\n"
"color: rgb(15, 15, 15);\n"
"font-size: 20px;\n"
"font-family: \"Arial Black\";\n"
"}\n"
"\n"
"\n"
"QPushButton:hover{\n"
"color: rgb(255, 17, 0);\n"
"background-color: rgb(215, 97, 0);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border: 3px inset rgb(93, 49, 0);\n"
"color: rgb(15, 15, 15);\n"
"background-color: rgb(255, 17, 0);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"background-color: #cccccc; /* Cinza */\n"
"border: 2px solid #999999;\n"
"color: #666666; /* Texto cinza escuro */\n"
"}\n"
"")
        self.btn_stop.setCheckable(False)
        self.btn_stop.setChecked(False)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_5.addWidget(self.btn_stop)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.red)
        self.yellow_frame = QtWidgets.QFrame(self.centralwidget)
        self.yellow_frame.setMaximumSize(QtCore.QSize(16777215, 54))
        self.yellow_frame.setStyleSheet("/*background-color: rgb(251, 255, 0);")
        self.yellow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.yellow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.yellow_frame.setObjectName("yellow_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.yellow_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.yellow_frame)
        self.label_5.setStyleSheet("    color: rgb(255, 137, 1);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.small_logo_label = QtWidgets.QLabel(self.yellow_frame)
        self.small_logo_label.setMinimumSize(QtCore.QSize(50, 50))
        self.small_logo_label.setMaximumSize(QtCore.QSize(50, 50))
        self.small_logo_label.setText("")
        self.small_logo_label.setPixmap(QtGui.QPixmap("c:\\Users\\Alisson\\Documents\\projetos\\Prime-Survivor-Log-Bot-2\\src\\views\\ui\\../../assets/ps_small_logo.png"))
        self.small_logo_label.setScaledContents(True)
        self.small_logo_label.setObjectName("small_logo_label")
        self.horizontalLayout_4.addWidget(self.small_logo_label)
        self.label_6 = QtWidgets.QLabel(self.yellow_frame)
        self.label_6.setStyleSheet("    color: rgb(255, 137, 1);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.verticalLayout.addWidget(self.yellow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ps - Log Bot"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Prime Survivor<br/>Log Bot</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "Select Your Resolution :"))
        self.label_4.setText(_translate("MainWindow", "webhook :"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.check_test.setToolTip(_translate("MainWindow", "Activate test mode.\n"
"When activated, the bot will send events even without actual validation."))
        self.check_test.setText(_translate("MainWindow", "Test Mode"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.label_5.setText(_translate("MainWindow", "Johan is bob"))
        self.label_6.setText(_translate("MainWindow", "krz also is bob"))
